### PR TITLE
pycurl speed  & verbose options

### PR DESCRIPTION
**Pull request by cesterlizi**
Hi

I've added pycurl options for  upload and download rate limit  and verbose

Carlos

### CODE REVIEW

**Comment by designerror** [comment]
https://github.com/designerror/webdav-client-python/blob/master/webdav/client.py#L517-L518

**Comment by cesterlizi** [comment]
@designerror 

Lines 526 and 527 were duplicated with 506 and 507

https://github.com/designerror/webdav-client-python/blob/master/webdav/client.py#L506-L507

        try:
            if not os.path.exists(local_path):
                raise LocalResourceNotFound(local_path)

            urn = Urn(remote_path)

            if urn.is_dir():
                raise OptionNotValid(name="remote_path", value=remote_path)

            if os.path.isdir(local_path):
                raise OptionNotValid(name="local_path", value=local_path)

            if not os.path.exists(local_path):
                raise LocalResourceNotFound(local_path)

**Comment by designerror** [comment]
@cesterlizi 

This branch has conflicts. If you re-open the pull request and add description for the new parameters into README.md, README.rst file then i will apply that pull request.

**Comment by cesterlizi** [comment]
@designerror 
I've updated Readme and solved conflicts

**Pull request merged**
